import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { cookieToInitialState } from "wagmi";
import { getConfig } from "@/configs/wagmi";
import { headers } from "next/headers";
import { type ReactNode } from "react";
import { Toaster } from "@/components/ui/sonner";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: { children: ReactNode }) {
  const initialState = cookieToInitialState(
    getConfig(),
    (await headers()).get("cookie")
  );

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 border-x-[1px] border-primary border-dashed h-screen">
          <Providers initialState={initialState}>
            {props.children}
            <Toaster />
            <Analytics />
          </Providers>
        </div>
      </body>
    </html>
  );
}
